[workspace]
members = [
    "crates/specification-core",
    "crates/specification-core-serde",
    "crates/specification-core-macros",
]
resolver = "3"

[workspace.package]
edition = "2024"
rust-version = "1.85"
version = "0.1.0"
license = "MIT"
repository = "https://github.com/SoundBlaster/specification-core-rs"
homepage = "https://github.com/SoundBlaster/specification-core-rs"

[workspace.lints.rust]
missing_docs = "deny"
unsafe_code = "deny"

[workspace.lints.rustdoc]
bare_urls = "deny"
broken_intra_doc_links = "deny"
private_intra_doc_links = "deny"
